/* #3 Assign unique random values to the array elements, that is, you want to fill the array
with random numbers, but each number in the array must not occur more than once. When
designing such an algorithm, a special situation must be highlighted at once - if the size of the
array is greater than the number of different random numbers generated by PRNG generator, it
will be impossible to solve the problem.
*/
#include <iostream>
using namespace std;
int main()
{
    int arr[3][6], i, j, counter = 0;
    float arithmetic_mean, summ, summ1, summ2, summ3, summ4, summ5;
    for (i = 0; i < 3; i++)
    {
        for (j = 0; j < 6; j++)
        {
            cout << "Enter arr: "
                 << "[" << i << "]"
                 << "[" << j << "] ";
            cin >> arr[i][j];
            
        }
        cout << endl;
    }

    cout << "Entered 2D Array: " << endl;

    for (i = 0; i < 3; i++)
    {
        for (j = 0; j < 6; j++)
        {
            cout << arr[i][j] << " ";
        }
        cout << endl;
    }

    for (i = 0; i < 3; i++)
    {

        if (arr[i][0] > 0)
        {
            summ += arr[i][0];
            counter++;
            cout << "Arithmetic mean column 1 = " << summ / counter << endl;
        }
        if (arr[i][1] > 0)
        {
            summ += arr[i][1];
            counter++;
            cout << "Arithmetic mean column 2  =  " << summ / counter << endl;
        }
        if (arr[i][2] > 0)
        {
            summ += arr[i][2];
            counter++;
            cout << "Arithmetic mean column 3  = " << summ / counter << endl;
        }
        if (arr[i][3] > 0)
        {
            summ += arr[i][3];
            counter++;
            cout << "Arithmetic mean column 4  = " << summ / counter << endl;
        }
        if (arr[i][4] > 0)
        {
            summ += arr[i][4];
            counter++;
            cout << "Arithmetic mean column 5  = " << summ / counter << endl;
        }
        if (arr[i][5] > 0)
        {
            summ += arr[i][5];
            counter++;
            cout << "Arithmetic mean column 6  =  " << summ / counter << endl;
        }
    }
    return 0;
}
